// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATo40hp3RrxyLNR4gqg2ul9W-pgj6K6c8',
    appId: '1:229509449174:web:00757d313a7fb8affd5077',
    messagingSenderId: '229509449174',
    projectId: 'upshot-6afce',
    authDomain: 'upshot-6afce.firebaseapp.com',
    storageBucket: 'upshot-6afce.appspot.com',
    measurementId: 'G-S82VXYGPD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlwpauZ5Wd1QCB0r-ryov173IpMtixfIQ',
    appId: '1:229509449174:android:89faaab215d3b56afd5077',
    messagingSenderId: '229509449174',
    projectId: 'upshot-6afce',
    storageBucket: 'upshot-6afce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyXDC7pr6pX4LG6BNzQ4ANB5gL50uiSms',
    appId: '1:229509449174:ios:cb39ff6d846319ecfd5077',
    messagingSenderId: '229509449174',
    projectId: 'upshot-6afce',
    storageBucket: 'upshot-6afce.appspot.com',
    iosClientId: '229509449174-doe3io994e4fitrjod30t89br137nose.apps.googleusercontent.com',
    iosBundleId: 'com.upshot.app',
  );
}
